### ISSUE TITLE
Example using discretized_mix_logistic_loss

### ISSUE THREAD

**Issue by zhang-jian** [openAGI/models#1]
Hi,
Is there a small example using discretized_mix_logistic_loss function? I do not understand the last dim of predictions and inputs:

predictions: 4D tensor or array, [batch_size, width, height, **out_channels**] predictions of the network .
inputs: 4D tensor or array, [batch_size, width, height, **num_classes**] ground truth labels or target labels.

Regards,

J

**Comment by n3011** [comment]
@zhang-jian There's no simple example available for now.  

This los is used for generative models (e.g. to generate images). Here inputs are the original input images batch used for training and predictions are the predicted distribution for the corresponding input batch. Here num_classes (3 for RGB images) is not necessary equal to out_channels (is the distribution dimensions from which RGB values are sampled.)

**Comment by zhang-jian** [comment]
@n3011 Thanks.
There are several lines that it isn't clear to me.
At line: 
<pre>
nr_mix = int(predictions_shape[-1] / 10)
</pre>
**What is 10 represent?**

mean is computed as
<pre>
means = tf.concat([tf.reshape(means[:, :, :, 0, :], [
                          inputs_shape[0], inputs_shape[1], inputs_shape[2], 1, nr_mix]), m2, m3], axis=3)
</pre>
What are m2 and m3 represent here?
And finally, what is <pre>1. / 255.</pre>?

Thanks a million!

J
